### ISSUE TITLE
Appveyor no longer building head of master or pull requests

### ISSUE THREAD

**Issue by ricksladkey** [VsVim/VsVim#2510] opened 2019-04-29 03:43 UTC
Probably because of the VsVim org change, appveyor no longer appears to be automatically building the head of master or any pull requests.

**Comment by TKumadaki** [comment] 2019-04-29 04:03
Is this the cause of my PR check not ending?
For now, I would like to wait for response from @jaredpar.

**Comment by ricksladkey** [comment] 2019-04-29 05:17
I believe so. I don't have access to the section of the project that configures CI checks, but it makes sense. My own fetch from the upstream works correctly without reconfiguration so I believe there are redirects, but I'm sure @jaredpar will know what to do.

**Comment by jaredpar** [comment] 2019-04-29 15:47
This should be fixed now. I just had to change the repository link to include the organization.

**Comment by jaredpar** [comment] 2019-04-29 17:28
Hmm, doesn't appear to be actually fixed. The builds are running but status isn't being shown.

**Comment by jaredpar** [comment] 2019-04-30 01:06
Fixed now and validated with #2511

**Closed by jaredpar** 2019-04-30 01:06 UTC
Labels: continuous integration
