### ISSUE TITLE
visual block append will append to end of line, not end of selected block

### ISSUE THREAD

**Issue by jmegner** [VsVim/VsVim#2676] opened 2019-07-08 22:53 UTC
**Describe the bug**
If you do a visual block append (C-V, select some lines, 'A' to append) on the appended characters append at the end of the line

**To Reproduce**
1. Start out with four lines of "111".
2. Visual block select the first column of the four lines.
3. Do a uppercase-a command and append '#'.
4. Notice that each line is "111#" instead of the correct "1#11"

**Environment (please complete the following information):**

- Visual Studio version: Visual Studio 2015 Enterprise Update 3 (14.0.25431.01)
- VsVim version: 2.7.0.0
- Check(Type 'x') any that are installed:
    - [ ] ReSharper
    - [ ] Visual Assist

**Comment by ricksladkey** [comment] 2019-07-08 23:49
This issue is a duplicate of the recently reported issue #2667 and was fixed in PR #2668.

**Closed by ricksladkey** 2019-07-08 23:49 UTC
Labels: duplicate
