### ISSUE TITLE
Exception in code relating to clipboard

### ISSUE THREAD

**Issue by cbates-** [VsVim/VsVim#2460] opened 2019-02-15 13:42 UTC
VS 2015 Pro v14.0.25431.01 Update 3
VsVim 2.60

I see this exception several times almost every day:
    <description>System.Runtime.InteropServices.COMException (0x800401D0): OpenClipboard Failed (Exception from HRESULT: 0x800401D0 (CLIPBRD_E_CANT_OPEN))&#x000D;&#x000A;   at System.Runtime.InteropServices.Marshal.ThrowExceptionForHRInternal(Int32 errorCode, IntPtr errorInfo)&#x000D;&#x000A;   at System.Windows.Clipboard.CriticalSetDataObject(Object data, Boolean copy)&#x000D;&#x000A;   at System.Windows.Clipboard.SetDataInternal(String format, Object data)&#x000D;&#x000A;   at System.Windows.Clipboard.SetText(String text, TextDataFormat format)&#x000D;&#x000A;   at System.Windows.Clipboard.SetText(String text)&#x000D;&#x000A;   at **Vim.UI.Wpf.Implementation.Misc.ClipboardDevice**.&lt;&gt;c__DisplayClass4_0.&lt;SetText&gt;g__action|0()&#x000D;&#x000A;   at Vim.UI.Wpf.Implementation.Misc.ClipboardDevice.TryAccessClipboard(Action action, Int32 retryCount, Int32 pauseMilliseconds)</description>

This morning it occurred after these keystrokes in normal mode:
gg
d2d

A wide variety of actions seem to trigger it.
A dialog announcing that an exception has occurred pops up; after clearing that, everything seems to work as expected.

**Comment by jaredpar** [comment] 2019-02-15 19:34
Thanks for reporting. 

Thought I had caught all places where it could throw but looks like I missed on. 

The fix here though is really not a fix. When this happens it's because the Windows clipboard is in a broken state. The only thing VsVim can do is catch the exception and report a diagnostic that this is happening.

**Comment by ricksladkey** [comment] 2019-05-01 03:35
The code in question does in fact try five times with a delay of 100ms between tries. Only then does it display a dialog box. The only possible changes we could make are to:

- ignore the error
- try more times
- wait longer between times

Since we don't plan to ignore the error and since it is already doing a fair number of retries and standard delays, I am going to close this as won't fix.

**Closed by ricksladkey** 2019-05-01 03:35 UTC
Labels: won't fix

**Comment by ricksladkey** [comment] 2019-05-23 15:21
Correction, we **do** plan to ignore clipboard exceptions (by default) and that was implemented in PR #2521. Closing this instead as a duplicate of the older issue #2067.
