### ISSUE TITLE
Macro leaves text object selection behavior out of sync with cursor position

### ISSUE THREAD

**Issue by adam-c-anderson** [VsVim/VsVim#2632] opened 2019-06-12 20:12 UTC
**Describe the bug**
From experimentation, it appears that playing a macro may leave VsVim thinking the cursor is somewhere to the left of where it actually is, for the purposes of selecting text for certain motions, specifically `i[`, `a[`, `i(`, and `a(`.

**To Reproduce**
 I was using a macro to reformat some F# union cases like this:

```fsharp
        | ACase e -> sprintf "ACase. Exception:%A" e
```

I used the following macro, starting with the cursor positioned somewhere on the case label (`ACase`): ```yiwf>a (Some ex, "SomePrefix.^R"", [], [("", box e, false)])^[lDF"i```

This resulted in the following text, with the cursor in insert mode positioned between the empty quotes:

```fsharp
        | ACase e -> (Some ex, "SomePrefix.ACase", [], [("", box e, false)])
```

On this case, I didn't actually want that entire tuple, so I exited insert mode and entered ```di[```. Nothing happened and a system chime played. Attempting to use visual mode to select inside the square brackets didn't work either. Using the motion ```i(``` operated on the entire outer tuple (the entire right side of the arrow).

After a little experimentation, I noticed that what was happening was VsVim was acting as if the cursor was two characters left of its actual position. Exiting insert mode puts the cursor on the opening double quote in the tuple in the list. Moving right to the closing quote, the problem persists. Moving right one more time to the comma, now the ```i(``` and ```i[``` behave as expected.

It appears that performing some jump such as to end of line with `$` corrects this situation; after doing so, I can navigate back to that opening double quote and operate on the ```i[``` block as expected.

This issue only appears to affect these text object motions as far as I can tell. For example, if I enter visual mode on that opening quote and move right once to the closing quote and press `d`, the expected result occurs: the string is deleted, not two characters two to the left.

**Expected behavior**
Inner/around text object selection works based on the displayed position of the cursor after playing the above macro on the above text.

**Screenshots**

**Environment (please complete the following information):**

- Visual Studio version: 2019 / 16.1.1
- VsVim version: 2.7.0.0
- Programming Language: F#
- Check(Type 'x') any that are installed:
    - [ ] ReSharper
    - [ ] Visual Assist

**Additional context**

Note:
The following is written about contributing.
https://github.com/VsVim/VsVim/blob/master/CONTRIBUTING.md

General Keyboard configuration problems are described below.
https://github.com/VsVim/VsVim/issues/2527

**Comment by ricksladkey** [comment] 2019-06-13 00:05
Thanks for filing a detail bug report! Although you have found a real bug which I can reproduce, I am unable to reproduce any differences in the behavior of, say, `di[` in your example depending on whether a macro has previously been run or not.

A simpler example of the bug you are reporting occurs in this example:

```
"foo" ("", true)
```

If you position the caret on either of the two adjacent double quotes or on the opening parenthesis, `di(` does not delete the parenthesized characters. If you position the caret on any character from the comma through the closing parenthesis, it works correctly.

By comparison, this simpler example works as expected, which shows that the preceding string is contributing to the problem:

```
any text but a string literal ("", true)
```

The bug is that the presence of two strings on the same line separated by an unmatched parenthesis is being incorrectly parsed as though it were one longer string, something like this:

```
"foo (", true)
```

but only when the context point is on or with the second string.

This bug was probably introduced in PR #2570, which was merged just prior to the release of 2.7.0. I will submit a pull request that fixes this and adds a unit test.

In the mean time, @adam-c-anderson, can you please try to find a repro for `di[` ever working correctly in your example? I can't ever make it work correctly with 2.7.0, even if a macro has never been played, but according to your report, it should work before a macro has been replayed or after a macro has been replayed and some caret jumps have occurred.

**Comment by ricksladkey** [comment] 2019-06-13 00:59
As an F# programmer, you will appreciate the irony that the bug fix was a line that assigned a value to a mutable variable. Also, this is my shortest bug fix ever: changing the indentation on a line by deleting whitespace.

**Comment by adam-c-anderson** [comment] 2019-06-13 13:08
>  can you please try to find a repro for di[ ever working correctly in your example?

You're right, when the cursor is positioned anywhere within the string literal, those text block motions don't work. The macro was not at all related.

> As an F# programmer, you will appreciate the irony that the bug fix was a line that assigned a value to a mutable variable.

😆

**Comment by adam-c-anderson** [comment] 2019-06-13 13:17
Overall I like significant whitespace, but code like what you fixed there showcases where it can become tricky: when indentation needs to be at the same level as expressions 10+ lines above. Normally I try to write code so that each scope stays at the same indent level or increases (e.g. by putting that `if` expression in its own function), but that's easier said than done with that particular function there!

**Closed** 2019-06-14 19:30 UTC
Labels: bug
