### ISSUE TITLE
EasyMotion workaround nerfed by vsvim update

### ISSUE THREAD

**Issue by keithn** [VsVim/VsVim#2043] opened 2017-12-19 01:18 UTC
No idea why these two programs still can't work together.... but there was a work around where if you did nmap <silent> \\ :vsc EasyMotion.Navigate<CR>:
you could use easymotion and VsVim wouldn't execute the letter, you just had to hit Esc after the easy motion.   But now somethings changed where easy motion can't see the letter pressed in command mode.  
So now you can't use easy motion at all.  Not sure if this is an easy motion / vsvim or visual studio change.

**Comment by keithn** [comment] 2018-03-19 01:36
Just a FYI for others looking for a work around, AceJump ( https://marketplace.visualstudio.com/items?itemName=jsturtevant.AceJump ) is an alternative that disables VsVim while doing its search.  Works well

**Comment by pleasenophp** [comment] 2018-05-03 08:12
Thank you very much! AceJump works perfectly!

**Comment by ricksladkey** [comment] 2019-05-11 06:25
Closing as duplicate of external issue https://github.com/jaredpar/EasyMotion/issues/21.

**Closed by ricksladkey** 2019-05-11 06:25 UTC
