### ISSUE TITLE
[VSMac] Cannot edit text when accessing insert mode from movements

### ISSUE THREAD

**Issue by one-adam-nolan** [VsVim/VsVim#2811] opened 2020-04-09 16:09 UTC
**Describe the bug**
When accessing insert mode from a movement  like "cw" or "a", existing text seems to be read only.

**To Reproduce**
1. Navigate to a word use "cw" to clear the word and go to insert mode
2. Press backspace
3. You will get a system alert and the cursor does not clear the text

**Expected behavior**
The text is editable

**Screenshots**

**Environment (please complete the following information):**

- Visual Studio version: VS for Mac 8.5.1 (build 42)
- VsVim version: 2.8.0.5
- Programming Language: C# (Xamarin)
- Check(Type 'x') any that are installed:
    - [ ] ReSharper
    - [ ] Visual Assist

Note:
The following is written about contributing.
https://github.com/VsVim/VsVim/blob/master/CONTRIBUTING.md

General Keyboard configuration problems are described below.
https://github.com/VsVim/VsVim/issues/2527

**Comment by nosami** [comment] 2020-04-09 17:49
Hi @one-adam-nolan 

Did you do this in your `~/.vsvimrc`? Backspace is broken in Vim by default but maybe I should work on changing the default on VSMac because this has come up a few times now.

```vim
set backspace=indent,eol,start
```

**Comment by one-adam-nolan** [comment] 2020-04-09 19:28
@nosami 🏆 That was it!! Do you want me to close this or?

**Comment by nosami** [comment] 2020-04-10 04:35
I guess we should keep this open. I need to do some work to improve the default experience on VSMac.

**Comment by nosami** [comment] 2020-04-10 08:54
Looks like this is supposed to work but something isn't wired up correctly on Mac.

https://github.com/VsVim/VsVim/blob/f648e644b3c363569710bcd2876bc9eacdad1e3a/Src/VimCore/Vim.fs#L786-L794

**Comment by nosami** [comment] 2020-04-12 17:17
@one-adam-nolan Now I'm quite confused.

I am certain that I saw the same behaviour when there was no ~/.vimrc or ~/.vsvimrc file set. But after testing without an rc file, it seems that backspace is indeed set to `indent, eol, start` by default.

<img width="901" alt="image" src="https://user-images.githubusercontent.com/667194/79075243-8a6f5e00-7ce9-11ea-860a-922ff5b2a793.png">

You can verify this like I have by opening the Vim output pad and then running the command `set backspace?`

Is it possible that you have a `~/.vimrc` file lurking around somewhere that is overriding this?

**Comment by one-adam-nolan** [comment] 2020-04-12 19:33
@nosami I created a .vimrc to map jj to escape....So that might be the issue!

**Comment by nosami** [comment] 2020-04-13 10:01
I'm going to close this. As far as I can tell, this is working as designed. Thanks for reporting though, this might help someone else to diagnose the issue in the future.

**Closed by nosami** 2020-04-13 10:01 UTC
Labels: vs4mac integration
