### ISSUE TITLE
Do you have plan to make vsvim compatible with vs easymotion?

### ISSUE THREAD

**Issue by 9527KGG** [VsVim/VsVim#1988] opened 2017-08-18 00:05 UTC
Some one also mentions it here: https://github.com/jaredpar/EasyMotion/issues/21

Really want it. Thanks.

**Comment by kinsung** [comment] 2017-10-07 06:47
This is very useful.

**Comment by ricksladkey** [comment] 2019-05-11 06:24
Closing as duplicate of external issue https://github.com/jaredpar/EasyMotion/issues/21.

**Closed by ricksladkey** 2019-05-11 06:24 UTC
