### ISSUE TITLE
Configure Key Bindings from vimrc

### ISSUE THREAD

**Issue by exyi** [VsVim/VsVim#1885] opened 2016-12-16 20:01 UTC
I'd like to configure VsVim's keybinding options (the GUI options) from vimrc, so I could easily transfer them between computers. Setting caret and background color would also be nice.

Is that somehow possible? I could not find it anywhere nor in the code - where are these settings located in the code? Maybe I could craft something myself ;)

**Comment by oysteinkrog** [comment] 2016-12-31 15:33
Create a .vsvimrc file and source whatever files you want.
I have dedicated files for keybindings etc that I source from both my .vimrc and .vsvimrc.

**Comment by exyi** [comment] 2016-12-31 17:23
I already use a .vsvimrc file, but I don't know how to configure if the keybinding is handled by Vsvim or VisualStudio. I mean this window: ![image](https://cloud.githubusercontent.com/assets/7894687/21578571/00a9e0be-cf86-11e6-87ea-afc8ab7046fb.png)

**Comment by jaredpar** [comment] 2017-01-01 15:55
Right now there is no way to do this.  Actually the first time I've gotten this request.  Let me think about it a bit.

**Comment by ricksladkey** [comment] 2019-05-12 01:21
Although this issue is older, I'm closing it as a duplicate of #1921.

**Closed by ricksladkey** 2019-05-12 01:21 UTC
Labels: feature request, visual studio integration
