### ISSUE TITLE
Unknown options

### ISSUE THREAD

**Issue by pedrofernandesfilho** [VsVim/VsVim#2658] opened 2019-06-26 16:43 UTC
I'm getting some erros when open VS with VsVim:
nknown option: undodir
```
Unknown option: backupdir
Unknown option: directory
Unknown option: belloff
Unknown option: t_Co
Error on line 16: Parse error
Unknown function: has
Error on line 31: Parse error
Error on line 37: Parse error
Unknown option: encoding
Unknown option: relativenumber
Error on line 63: Parse error
Unknown option: ruler
Unknown option: wildmenu
```

My .vimrc:
[vimrc.txt](https://github.com/VsVim/VsVim/files/3331068/vimrc.txt)

![VsVim_errors](https://user-images.githubusercontent.com/508725/60187932-da397300-9804-11e9-8820-7e091d9357c4.PNG)

1.  Put configurations on .vimrc
2.  Open VS
3.  Open some file
4.  See error

- Visual Studio version: 2017 Pro and 2019 Enterprise
- VsVim version: 2.7.0.0
- Programming Language: C#
- Check(Type 'x') any that are installed:
    - [ ] ReSharper
    - [ ] Visual Assist

**Comment by ricksladkey** [comment] 2019-06-26 17:16
This is a duplicate of issue #2585 and the problem has already been resolved in PR #2589.

The problem occurs when you do not have a vsvim rc file but you do have a vim rc file. Previously VsVim would attempt to load your vim rc file, but would suppresses the reporting of any errors that you see. In VsVim 2.7.0, due to a bug, those errors (which always occurred), are now being reported.

To prevent these errors from being displayed you can:

1. Upgrade to the latest nightly build of VsVim (which includes a fix for that problem), or
2. You can create a vsvim rc file and only put in that file commands that VsVim understands.

The specific error you are getting is due to VsVim not expanding environment variables in the same situation that vim would expand them, but VsVim has always had that problem.

**Closed by ricksladkey** 2019-06-26 17:16 UTC
