### ISSUE TITLE
VsVim on Visual Studio for Mac 8.8 Install failed

### ISSUE THREAD

**Issue by thatnerdjosh** [VsVim/VsVim#2862] opened 2020-11-14 21:44 UTC
**Describe the bug**
When I try to install this extension using the gallery, it produces the below dialog.

<img width="867" alt="Screen Shot 2563-11-15 at 04 42 24" src="https://user-images.githubusercontent.com/5251847/99157607-f8a35580-26fc-11eb-9b16-6c5ee19f5cc7.png">

**To Reproduce**

1.  Go to Extensions
2.  Click on Gallery
3.  Search for VIM
4.  Install
5.  See error

**Expected behavior**
Expected it to install

**Environment (please complete the following information):**

- Visual Studio version: Visual Studio for Mac Professional v8.8 (build 2913)
- VsVim version: 2.8.0.7
- Programming Language: N/A
- Check(Type 'x') any that are installed:
    - [ ] ReSharper
    - [ ] Visual Assist

**Comment by nosami** [comment] 2020-11-14 23:16
Sorry about that, I didn't test on 8.8 before publishing but I can reproduce.

I'm not sure why this error is happening yet as there is nothing in the log file, but for now you can follow the instructions [here](https://github.com/VsVim/VsVim/issues/2837#issuecomment-645450687) to install

**Comment by thatnerdjosh** [comment] 2020-11-15 01:51
Thank you @nosami I could potentially try and trace it down, would be a good learning experience. That is, unless you are already on it.

Let me know :D

**Comment by nosami** [comment] 2020-11-15 09:57
Seems like there could be a bug in VSMac. I can't install any extension from the gallery. I'll file an issue.

**Comment by thatnerdjosh** [comment] 2020-11-15 10:19
Ok, yeah it works fine on Windows

**Comment by nosami** [comment] 2020-11-15 10:26
![image](https://user-images.githubusercontent.com/667194/99182441-ec36f100-272c-11eb-9021-7fd99987241e.png)
None of these extensions will install via the gallery.

**Comment by mrward** [comment] 2020-11-16 08:53
Pretty sure this is problem with the addin server. I had the same problem back with 8.7. The problem is that the addin needs to be published for 8.8 not 8.8.0 otherwise the download url is wrong. Unfortunately 8.8 is not available in the drop down when publishing on addins.monodevelop.com.

**Comment by nosami** [comment] 2020-11-16 09:18
This is fixed now. The VSMac team needed to make a change to the server hosting the gallery. Thanks for reporting!

**Closed by nosami** 2020-11-16 09:18 UTC
Labels: vs4mac integration
