### ISSUE TITLE
VsVim for Mac: Second curly bracket spacing does not match first

### ISSUE THREAD

**Issue by funseiki** [VsVim/VsVim#2784] opened 2020-02-18 02:40 UTC
**Describe the bug**
After curly brackets `{}` are autocompleted, the pressing the `enter/return` key before the closing bracket causes its indentation to be back one level.

E.g.

**To Reproduce**

1.  Type the following:
```
     if(1==1)
     { }
```
2.  Set cursor just before `}` and press `enter`
3.  See the following:
```
     if(1==1)
     { 
}
```

**Expected behavior**
We should probably see the the indentation matching. E.g.
```
     if(1==1)
     { 
     }
```

**Environment (please complete the following information):**

- Visual Studio version: 8.5 Preview (8.5 build 2739). This also occurs on 8.4.5
- VsVim version: 2.8.0.1 (as well as 2.8.0.0)
- Programming Language: C#

**Additional context**
I've commented out most of my .vimrc and .vsvimrc files to no avail. I'll paste the .vimrc I'm using below, in case it's useful.

```.vimrc
set backspace=indent,eol,start
set relativenumber 
set nobackup        "no backup files
set noswapfile      "no swap files
set visualbell      "no beeping

" Use :W to save as well
command! W write

let mapleader = ","
nnoremap <S-h> gT
nnoremap <S-l> gt

" Split navigation
nnoremap <C-h> <C-W><C-H> 
nnoremap <C-j> <C-W><C-J> 
nnoremap <C-k> <C-W><C-K> 
nnoremap <C-l> <C-W><C-L> 

" Split resize
noremap ,, <C-W><
noremap .. <C-W>>
noremap -- <C-W>-
noremap == <C-W>+

nnoremap <leader>ev :vsplit $MYVIMRC<cr>
nnoremap <leader>sv :source $MYVIMRC<cr>

nnoremap <leader>b :!b<cr>
```

**Comment by funseiki** [comment] 2020-02-18 02:49
I just tried turning off the `Automatically format return` setting and that appears to do the trick. 

Disabling VsVim and leaving that setting on also formats the brackets with the proper indentation, so it looks like there is some conflict between the extension and that setting.

**Comment by nosami** [comment] 2020-02-18 11:11
Not sure what is going on here as I can't reproduce. I have `Automatically format return` turned on.

<img width="615" alt="image" src="https://user-images.githubusercontent.com/667194/74730874-dac4c500-523e-11ea-9fbb-e96f8bd1c855.png">

![return](https://user-images.githubusercontent.com/667194/74731108-4dce3b80-523f-11ea-8ff9-4bbd8b1aaa54.gif)

**Comment by funseiki** [comment] 2020-02-18 14:02
Weird. Not sure where the actual conflict is then (though I can still consistently reproduce it using the above method). 

This isn't the biggest deal (for me), though, since the aforementioned workaround works fine.

**Comment by funseiki** [comment] 2020-02-20 05:54
@nosami Gah so it looks like that workaround doesn't work for nested conditions. I am noticing that my indents are all spaces for some reason (even though the corresponding "expandtab" line in my .vimrc is commented out.

Nested weirdness:
![SmallVsVimCapture](https://user-images.githubusercontent.com/669439/74904712-7a3aa280-537a-11ea-8203-a6cbfdcd61d7.gif)

**Comment by nosami** [comment] 2020-02-23 13:09
> @nosami Gah so it looks like that workaround doesn't work for nested conditions. I am noticing that my indents are all spaces for some reason (even though the corresponding "expandtab" line in my .vimrc is commented out.

You can control spaces vs tabs in this dialog. Note that spaces are the default for C# :-

<img width="690" alt="image" src="https://user-images.githubusercontent.com/667194/75112656-ad608880-563d-11ea-87bf-b7a07f61af11.png">

**Comment by funseiki** [comment] 2020-02-23 17:46
Yep, saw that. Tried both and still having the issue, unfortunately.

**Comment by funseiki** [comment] 2020-03-06 21:19
I think we can close this one. I uninstalled and reinstalled visual studio and did the same with the VsVim extension and that looks to have solved it for the time being.

**Comment by nosami** [comment] 2020-03-07 09:42
@funseiki OK, let's close it. I still haven't encountered this problem. 

Please re-open if it happens again. Thanks!

**Closed** 2020-03-12 16:10 UTC
Labels: vs4mac integration

**Comment by Salam4nder** [comment] 2022-02-23 16:13
I am having this issue on 2 separate Macos machines on visual studio for Mac and VsVim. I've tried all the solutions here, still same issue...

**Comment by nosami** [comment] 2022-02-23 19:52
> I am having this issue on 2 separate Macos machines on visual studio for Mac and VsVim. I've tried all the solutions here, still same issue...

Which versions of VSMac and VSVim are you using?

**Comment by Salam4nder** [comment] 2022-02-23 20:13
> > I am having this issue on 2 separate Macos machines on visual studio for Mac and VsVim. I've tried all the solutions here, still same issue...
> 
> Which versions of VSMac and VSVim are you using?

Thanks for the reply.
VSMac : 8.10.19 (build 2)
VSVim: 2.8.0.14

**Comment by nosami** [comment] 2022-03-14 18:56
@Salam4nder I don't have a repro. I have never seen this issue and I've worked on plenty of different codebases so I'm not sure what's wrong.

Please share all your settings (both VsVim and VSMac) and maybe a sample solution where the issue manifests and I can take a look.
