### ISSUE TITLE
Incorrect cursor positioning with code lens enabled

### ISSUE THREAD

**Issue by IvanNazarov** [VsVim/VsVim#2719] opened 2019-09-02 06:59 UTC
![image](https://user-images.githubusercontent.com/22483501/64095613-f65b1280-cd67-11e9-9824-7d71b9007898.png)

**Comment by Marskey** [comment] 2019-09-02 12:27
omg， your font is beatiful, what is the name?

**Comment by IvanNazarov** [comment] 2019-09-02 12:45
> omg， your font is beatiful, what is the name?
https://github.com/tonsky/FiraCode

**Comment by jaredpar** [comment] 2019-09-02 17:14
Do you see this bug with a standard font or is it specific to the FiraCode font?

**Comment by IvanNazarov** [comment] 2019-09-02 17:57
Consolas size 11
![image](https://user-images.githubusercontent.com/22483501/64129325-14eef700-cdc4-11e9-9503-c69ff85ab822.png)

**Comment by IvanNazarov** [comment] 2019-09-02 18:07
Visual Studio Community 2019 16.2.3

VisualStudio.16.Release/16.2.3+29215.179
Microsoft .NET Framework
Version 4.8.03752

Installed Version: Community

Microsoft Visual C++ 2019
ADL Tools Service Provider   1.0
ASP.NET and Web Tools 2019   16.2.290.48383
ASP.NET Web Frameworks and Tools 2019   16.2.290.48383
Azure App Service Tools v3.0.0   16.2.290.48383
Azure Data Lake Node   1.0
Azure Data Lake Tools for Visual Studio   2.3.9000.0
Azure Functions and Web Jobs Tools   16.2.290.48383
Azure Stream Analytics Tools for Visual Studio   2.3.9000.0
C# Tools   3.2.1-beta4-19408-03+2fc6a04980f800c59e8ede97e6ae294ff47d666e
Common Azure Tools   1.10
CSS Tools 2019   1.1.2
Extensibility Message Bus   1.2.0 (d16-2@8b56e20)
IntelliCode Extension   1.0
Microsoft Azure HDInsight Azure Node   2.3.9000.0
Microsoft Azure Hive Query Language Service   2.3.9000.0
Microsoft Azure Stream Analytics Language Service   2.3.9000.0
Microsoft Azure Stream Analytics Node   1.0
Microsoft Azure Tools   2.9
Microsoft Azure Tools for Microsoft Visual Studio 0x10 - v2.9.20626.2
Microsoft Continuous Delivery Tools for Visual Studio   0.4
Microsoft JVM Debugger   1.0
Microsoft Library Manager   1.0
Microsoft MI-Based Debugger   1.0
Microsoft Visual C++ Wizards   1.0
Microsoft Visual Studio Tools for Containers   1.1
Microsoft Visual Studio VC Package   1.0
Mono Debugging for Visual Studio   16.2.6 (4cfc7c3)
Node.js Tools   1.5.10610.1 Commit Hash:529a87de2769e143655e31ea81795c42e5775ef8
NuGet Package Manager   5.2.0
ProjectServicesPackage Extension   1.0
ResourcePackage Extension   1.0
SQL Server Data Tools   16.0.61906.28070
Microsoft SQL Server Data Tools
ToolWindowHostedEditor   1.0
TypeScript Tools   16.0.10627.2001
Visual Basic Tools   3.2.1-beta4-19408-03+2fc6a04980f800c59e8ede97e6ae294ff47d666e
Visual F# Tools 10.4 for F# 4.6   16.2.0-beta.19321.1+a24d94ecf97d0d69d4fbe6b8b10cd1f97737fff4
Visual Studio Code Debug Adapter Host Package   1.0
Visual Studio Tools for Containers   1.0
Visual Studio Tools for Containers
VisualStudio.Mac   1.0
VsNerdXPackage Extension   1.0
VsVim   2.8.0.0
Xamarin   16.2.0.95 (d16-2@37df81894)
Xamarin Designer   16.2.0.375 (remotes/origin/d16-2@357d38ef4)
Xamarin Templates   16.3.117 (59a59e8)
Xamarin.Android SDK   9.4.1.0 (d16-2/ebd65c9)
Xamarin.Android Reference Assemblies and MSBuild support.
    Mono: mono/mono/2019-02@e6f5369c2d2
    Java.Interop: xamarin/java.interop/d16-2@d64ada5
    LibZipSharp: grendello/LibZipSharp/d16-2@caa0c74
    LibZip: nih-at/libzip/rel-1-5-1@b95cf3f
    ProGuard: xamarin/proguard/master@905836d
    SQLite: xamarin/sqlite/3.27.1@8212a2d
    Xamarin.Android Tools: xamarin/xamarin-android-tools/d16-2@6f6c969
Xamarin.iOS and Xamarin.Mac SDK   12.14.0.114 (c669116)

**Comment by Marskey** [comment] 2019-09-03 01:46
> Do you see this bug with a standard font or is it specific to the FiraCode font?
specific to the FiraCode font from now i see

**Comment by ricksladkey** [comment] 2019-09-06 06:07
This is a duplicate of issue #2709. We'll definitely get this fixed for 2.8.0! Thanks for filing an issue.

**Closed by ricksladkey** 2019-09-06 06:07 UTC
Labels: bug, need more data
