### ISSUE TITLE
Changing VsVim keyboard shortcut freezes VS2017

### ISSUE THREAD

**Issue by UnderHeavyDevelopment** [VsVim/VsVim#2478] opened 2019-03-09 13:43 UTC
**VS: 2017 Community 15.9.8
VsVim: 2.6.0.0
Resharper: no**

1.  Options/VsVim/Keyboard
(All shortcuts must be "Handled by Visual Studio")
2. Change for "Ctrl + M" to "Handled by VsVim"
3. Click OK
Freeze

**Comment by jaredpar** [comment] 2019-03-11 14:19
Sorry to hear that. Can you get a dump of VS when the freeze happens so I can take look? You can use taskmgr to create a dump here. Should be pretty easy to see what's going on once I have this.

**Comment by UnderHeavyDevelopment** [comment] 2019-03-11 22:06
I would not want to risk exposing any data through a dump, hope you understand.
However, I have reproduced this issue also on a different machine with VS 2017 Professional.
This time I was more patient, and freeze always takes 30 seconds after which settings are applied.
Strange thing is, after I killed VS couple times during this freeze, keyboard settings I had just modified completely vanished from the list - forever.

**Comment by jaredpar** [comment] 2019-03-15 22:07
> I would not want to risk exposing any data through a dump, hope you understand.

Definitely understand. If you can't share the dump though could you share the stack trace at the moment of the hang? That is what I really wanted to get from the dump. It will at least get me pointed in the right direction.

**Comment by UnderHeavyDevelopment** [comment] 2019-03-16 15:30
Sure, here is the call stack. Hope it helps. To debug, I'm missing `Vim.VisualStudio.Shared.pdb`, but compiling it on my own (build Release, branch VsVim-2.6.0), doesn't work - `"A matching symbol file was not found in this folder"`.
```
[Managed to Native Transition]	
Vim.VisualStudio.Shared.dll!Vim.VisualStudio.Extensions.SafeSetBindings(EnvDTE.Command command, System.Collections.Generic.IEnumerable<string> commandBindings)	Unknown
Vim.VisualStudio.Shared.dll!Vim.VisualStudio.Implementation.OptionPages.KeyboardSettingsControl.UpdateKeyBindings()	Unknown
Vim.VisualStudio.Shared.dll!Vim.VisualStudio.Implementation.OptionPages.KeyboardSettingsControl.Apply()	Unknown
Vim.VisualStudio.Shared.dll!Vim.VisualStudio.Implementation.OptionPages.KeyboardOptionPage.OnApply(Microsoft.VisualStudio.Shell.DialogPage.PageApplyEventArgs e)	Unknown
Microsoft.VisualStudio.Shell.11.0.dll!Microsoft.VisualStudio.Shell.DialogPage.DialogSubclass.WndProc(ref System.Windows.Forms.Message m)	Unknown
System.Windows.Forms.dll!System.Windows.Forms.NativeWindow.DebuggableCallback(System.IntPtr hWnd, int msg, System.IntPtr wparam, System.IntPtr lparam)	Unknown
[Native to Managed Transition]	
[Managed to Native Transition]	
Microsoft.VisualStudio.Shell.15.0.dll!Microsoft.Internal.VisualStudio.PlatformUI.DataSource.Invoke(string verb, object pvaIn, out object pvaOut)	Unknown
Microsoft.VisualStudio.Shell.UI.Internal.dll!Microsoft.VisualStudio.PlatformUI.VsCommand.Execute(object parameter)	Unknown
PresentationFramework.dll!MS.Internal.Commands.CommandHelpers.CriticalExecuteCommandSource(System.Windows.Input.ICommandSource commandSource, bool userInitiated)	Unknown
PresentationFramework.dll!System.Windows.Controls.MenuItem.InvokeClickAfterRender(object arg)	Unknown
WindowsBase.dll!System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate callback, object args, int numArgs)	Unknown
WindowsBase.dll!System.Windows.Threading.ExceptionWrapper.TryCatchWhen(object source, System.Delegate callback, object args, int numArgs, System.Delegate catchHandler)	Unknown
WindowsBase.dll!System.Windows.Threading.DispatcherOperation.InvokeImpl()	Unknown
WindowsBase.dll!System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(object state)	Unknown
WindowsBase.dll!MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(object obj)	Unknown
mscorlib.dll!System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, object state, bool preserveSyncCtx)	Unknown
mscorlib.dll!System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, object state, bool preserveSyncCtx)	Unknown
mscorlib.dll!System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, object state)	Unknown
WindowsBase.dll!MS.Internal.CulturePreservingExecutionContext.Run(MS.Internal.CulturePreservingExecutionContext executionContext, System.Threading.ContextCallback callback, object state)	Unknown
WindowsBase.dll!System.Windows.Threading.DispatcherOperation.Invoke()	Unknown
WindowsBase.dll!System.Windows.Threading.Dispatcher.ProcessQueue()	Unknown
WindowsBase.dll!System.Windows.Threading.Dispatcher.WndProcHook(System.IntPtr hwnd, int msg, System.IntPtr wParam, System.IntPtr lParam, ref bool handled)	Unknown
WindowsBase.dll!MS.Win32.HwndWrapper.WndProc(System.IntPtr hwnd, int msg, System.IntPtr wParam, System.IntPtr lParam, ref bool handled)	Unknown
WindowsBase.dll!MS.Win32.HwndSubclass.DispatcherCallbackOperation(object o)	Unknown
WindowsBase.dll!System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate callback, object args, int numArgs)	Unknown
WindowsBase.dll!System.Windows.Threading.ExceptionWrapper.TryCatchWhen(object source, System.Delegate callback, object args, int numArgs, System.Delegate catchHandler)	Unknown
WindowsBase.dll!System.Windows.Threading.Dispatcher.LegacyInvokeImpl(System.Windows.Threading.DispatcherPriority priority, System.TimeSpan timeout, System.Delegate method, object args, int numArgs)	Unknown
WindowsBase.dll!MS.Win32.HwndSubclass.SubclassWndProc(System.IntPtr hwnd, int msg, System.IntPtr wParam, System.IntPtr lParam)	Unknown
[Native to Managed Transition]	
```

**Comment by ricksladkey** [comment] 2019-04-27 05:59
A similar delay (when it occurs) can be induced by resetting the keyboard configuration, which doesn't involve VsVim at all, and so I don't think the delay is VsVim's fault per se, but Visual Studio's. Oddly Visual Studio sometimes seems to be able to reset the keyboard configuration quickly and other times it takes many seconds (the freeze), and I don't know what causes the variability.

**Comment by ricksladkey** [comment] 2019-05-27 03:23
The workaround here is just to wait; it will complete.  Because the delay is caused by Visual Studio changing the key bindings, not by VsVim, I am closing this issue.

**Closed by ricksladkey** 2019-05-27 03:23 UTC
Labels: need more data
