### ISSUE TITLE
"+y Causes exception.

### ISSUE THREAD

**Issue by mikehadlow** [VsVim/VsVim#2560] opened 2019-05-23 11:03 UTC
Microsoft Visual Studio 2019 version: 16.0.28916.169
VsVim 2.6.0.0
[ActivityLog.log](https://github.com/VsVim/VsVim/files/3211772/ActivityLog.log)

Copy to system clipboard ( "+y ) causes an exception in VS2019. It only happens the first time, after dismissing the warning, all subsequent tries pass.
![image](https://user-images.githubusercontent.com/223097/58247724-3e729e00-7d52-11e9-9543-91592f4581ad.png)
Attached the VS log file:

**Comment by ricksladkey** [comment] 2019-05-23 15:25
Thank you very much for taking the time to file an issue. This bug is a duplicate of the older issue #2067, which was closed by PR #2521.

VsVim at the head of master now ignores all clipboard exceptions by default. This feature will become available in VsVim 2.7.0, which we are tentatively planning to release soon.

**Closed by ricksladkey** 2019-05-23 15:25 UTC
