### ISSUE TITLE
CompositionFailedException: This part (Vim.Vim) cannot be instantiated

### ISSUE THREAD

**Issue by baldurk** [VsVim/VsVim#2249] opened 2018-07-12 11:34 UTC
Recently when starting VS 2015, whether I create a new project or open an existing one I get a popup like this:

![image](https://user-images.githubusercontent.com/661798/42630375-6480c7c4-85ce-11e8-9f27-244dccbe947b.png)

And in the [ActivityLog.xml](https://github.com/jaredpar/VsVim/files/2188392/ActivityLog.zip) is the exception in the subject.

Strangely, as far as I can tell nothing is broken or not working after that.

I can't tell you exactly when it started happening unfortunately, I was running a local build with a temp fix for #1777 for a long time, so I only recently jumped onto updated builds and started seeing it then. If it's possible to run older builds to bisect the problem I'm happy to do that I'm just not sure how from the VS extension gallery.

I was running with all extensions disabled and it still happens, so I don't think it's a conflict with something else.

**Comment by jaredpar** [comment] 2018-10-12 15:42
So far I've been unable to reproduce this. I've tried on a few different machines. There were a few reports of this so I believe it's real.

For anyone else who hits this in the future. Can you please do the following:

- Navigate to `%LOCALAPPDATA%\Microsoft\VisualStudio\<version>\Extensions`

Then upload + respond to this issue with a link to the file. This err file should have the information I need  to help track down the problem.

**Comment by baldurk** [comment] 2018-10-12 15:47
Sorry I might be missing something obvious, which file do you want from that folder?

**Comment by jaredpar** [comment] 2018-10-12 15:48
@baldurk sorry, I left that critical piece of information out 😦. Fixed that.

**Comment by baldurk** [comment] 2018-10-12 16:03
I don't have any error files in that folder :disappointed: . Just one folder per extension I have installed, plus `CompatibilityList.xml`, `extensions.en-US.cache`, `extensionSdks.en-US.cache`, `VSIXInstaller.extensions.en-US.cache`, `VSIXInstaller.extensionSdks.en-US.cache`.

I also looked in vsvim's folder, but nothing there either.

I noticed that for some reason VS hadn't auto-updated the extension, so I manually updated from 2.6.991 to 2.6.1221, but that didn't seem to  change anything.

**Comment by jaredpar** [comment] 2018-10-12 16:05
Hmm. I guess that error file logging didn't make it into Dev14 then. That's frustrating. May have to try and get a VM together.

**Comment by baldurk** [comment] 2018-10-12 16:19
I tried on VS2017 (Version 15.5.6). I wasn't clear what `<Version>` would be in the path, because I have three folders: 15.0, 15.0_67b17c2c, and 15.0_67b17c2cExp.

15.0 is completely empty, 15.0_67b17c2cExp has an Extensions folder but it looks old (hasn't been modified since 2017), so I assume 15.0_67b17c2c is the right one.

Unfortunately I still don't get any error files under there or in VsVim's folder. I've attached the VS2017's ActivityLog.xml which doesn't have the CompositionFailedException exception anymore. It does seem to be VsVim related - this log is from a run with all other extensions disabled, and if I have VsVim disabled I don't get the error.

[ActivityLog.zip](https://github.com/jaredpar/VsVim/files/2473817/ActivityLog.zip)

**Comment by jaredpar** [comment] 2018-10-12 17:59
Thanks for the log. Yeah this is mildly frustrating. Pondering other ways to get this information.

**Comment by baldurk** [comment] 2018-10-15 14:29
I compiled a local version of VsVim to experiment with mouse behaviour, and I still got this error. Unfortunately when trying to reproduce it and debug I couldn't. I'm not super familiar with VSIX but looking around it seems like you're intended to debug in a separate 'experimental' version of VS - and I could never get the exception to happen there, even after copying in and enabling all my other extensions.

It maybe suggests I've got some stale setting or leftover configuration or something, I'm not sure if that's helpful. If there's a way to debug the extension in the 'real' VS I can give that a go.

**Comment by ricksladkey** [comment] 2018-10-21 04:40
PR #2386 closed this defect, but it was merged into staging instead of master, so this issue was not closed automatically. I am closing it manually because staging is the release branch for the 2.6 release.

**Comment by baldurk** [comment] 2018-10-21 09:57
Works great for me in a few tests, thanks!

**Comment by dwo77** [comment] 2019-03-08 08:01
This bug is here again with 2.7.1324! Please reopen!

**Comment by ricksladkey** [comment] 2019-03-08 23:59
Re-opening.

@dwo77, can you give some more details about how the issue manifests itself. When you get a chance, please locate and attach activity log to this issue. Thanks.

**Comment by ricksladkey** [comment] 2019-05-12 00:14
Closing due to stalled investigation.

**Closed by ricksladkey** 2019-05-12 00:14 UTC
Labels: bug, need more data
