### ISSUE TITLE
CTRL + N  =>  Please use $IAsyncCompletionBroker and IAsyncCompletionSession to interact with completion.

### ISSUE THREAD

**Issue by tobser** [VsVim/VsVim#2572] opened 2019-05-27 08:40 UTC
If i hit CTRL+N in an edidor window VisualStudio notifies me about an NotImplementedException.

- Visual Studio version: VS 2019 16.1.1
- VsVim version: 2.6.0.0
- Programming Language: c#
- Check(Type 'x') any that are installed:
    - [ ] ReSharper
    - [ ] Visual Assist

**Additional context**

Here ist the StackTrace from the log:

```
System.NotImplementedException: Please use $IAsyncCompletionBroker and IAsyncCompletionSession to interact with completion. Use IAsyncCompletionBroker.IsCompletionSupported to check if feature is available and IAsyncCompletionBroker.GetSession to get the session.
   at Microsoft.VisualStudio.Language.Intellisense.Implementation.ShimCompletionSession.set_SelectedCompletionSet(CompletionSet value)
   at Vim.UI.Wpf.Implementation.WordCompletion.WordCompletionSessionFactoryService.Vim.IWordCompletionSessionFactoryService.CreateWordCompletionSession(ITextView textView, SnapshotSpan wordSpan, IEnumerable`1 wordCollection, Boolean isForward)
   at Vim.Modes.Insert.InsertMode.StartWordCompletionSession(Boolean isForward)
   at Vim.Modes.Insert.InsertMode.ProcessWordCompletionNext(KeyInput keyInput)
   at Vim.Modes.Insert.InsertMode.Process(KeyInput keyInput)
   at Vim.Modes.Insert.InsertMode.Vim-IMode-Process(KeyInput keyInput)
   at Vim.VimBuffer.ProcessOneKeyInput(KeyInput keyInput)
   at &lt;StartupCode$Vim-Core&gt;.$VimBuffer.processSet@564(VimBuffer x, FSharpRef`1 processResult, KeyInputSet keyInputSet)
   at Vim.VimBuffer.ProcessCore(KeyInputSet keyInputSet)
   at Vim.VimBuffer.Process(KeyInput keyInput)
   at Vim.VimBuffer.Vim-IVimBuffer-Process(KeyInput keyInput)
   at Vim.UI.Wpf.VimKeyProcessor.TryProcess(KeyInput keyInput)
   at Vim.VisualStudio.Implementation.Misc.VsVimKeyProcessor.TryProcess(KeyInput keyInput)
   at Vim.UI.Wpf.VimKeyProcessor.TextInput(TextCompositionEventArgs args)
   at Microsoft.VisualStudio.Text.Editor.Implementation.KeyProcessorDispatcher.&lt;&gt;c.&lt;DispatchTextInputEvents&gt;b__6_0(KeyProcessor p, TextCompositionEventArgs args)
   at Microsoft.VisualStudio.Text.Editor.Implementation.KeyProcessorDispatcher.&lt;&gt;c__DisplayClass10_1`1.&lt;Dispatch&gt;b__0()
   at Microsoft.VisualStudio.Text.Utilities.GuardedOperations.CallExtensionPoint(Object errorSource, Action call)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
```

**Comment by ricksladkey** [comment] 2019-05-27 15:24
Thank you for taking the time to file a bug. This issue is a duplicate of #2466 and was fixed in PR #2549. The exception and stack trace will no longer in VsVim 2.7.0, which we are planning are releasing this week.

**Closed by ricksladkey** 2019-05-27 15:24 UTC
Labels: duplicate
