### ISSUE TITLE
vs2017, set clipboard=unnamed,vs encounter an exception

### ISSUE THREAD

**Issue by arteny** [VsVim/VsVim#2067] opened 2018-01-21 21:12 UTC
Absolutely same issue as #2001 . You closing all this issues referencing each to other, but it is not solved.
Almost each second copy (y) show me error, referencing to log i got:
```
 <entry>
    <record>1026</record>
    <time>2018/01/21 21:05:07.717</time>
    <type>Error</type>
    <source>Editor or Editor Extension</source>
    <description>System.Runtime.InteropServices.COMException (0x800401D0): &#x041E;&#x0448;&#x0438;&#x0431;&#x043A;&#x0430; &#x043F;&#x0440;&#x0438; &#x0432;&#x044B;&#x0437;&#x043E;&#x0432;&#x0435; OpenClipboard (Exception from HRESULT: 0x800401D0 (CLIPBRD_E_CANT_OPEN))&#x000D;&#x000A;   at System.Runtime.InteropServices.Marshal.ThrowExceptionForHRInternal(Int32 errorCode, IntPtr errorInfo)&#x000D;&#x000A;   at System.Windows.Clipboard.CriticalSetDataObject(Object data, Boolean copy)&#x000D;&#x000A;   at System.Windows.Clipboard.SetDataInternal(String format, Object data)&#x000D;&#x000A;   at System.Windows.Clipboard.SetText(String text, TextDataFormat format)&#x000D;&#x000A;   at System.Windows.Clipboard.SetText(String text)&#x000D;&#x000A;   at Vim.UI.Wpf.Implementation.Misc.ClipboardDevice.&lt;&gt;c__DisplayClass4_0.&lt;SetText&gt;b__0()&#x000D;&#x000A;   at Vim.UI.Wpf.Implementation.Misc.ClipboardDevice.TryAccessClipboard(Action action, Int32 retryCount, Int32 pauseMilliseconds)&#x000D;&#x000A;--- End of stack trace from previous location where exception was thrown ---&#x000D;&#x000A;   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)</description>
  </entry>
```

**Comment by jaredpar** [comment] 2018-01-22 16:08
That should be fixed. Maybe there is some path on which I'm not properly catching the exception. Will check. 

Note: this error happens when the windows clipboard is in a bad state. There is nothing I can do to fix that, all I can do is suppress the exception. Hence any yank commands that occur when the clipboard is in this state won't actually copy to the windows clipboard.

**Comment by ricksladkey** [comment] 2019-05-01 18:32
Maybe we should increase the number of retries from 5 to 10 and / or increase the delay from 100ms to 200ms?

The only other option is to close this issue as "by design", and I'm certain @arteny would not be happy with that outcome.

**Comment by jaredpar** [comment] 2019-05-03 16:10
I don't think increasing the count / delay will help much here. It seems based on the user reports that the cilpboard can get into a really bad state at times. To the point that operations don't even fail fast, they take considerable amount of time to fail. Increasing the count / delay will exacerbate that situation. 

The idea I'd been thinking of is the following: when we detect the clipboard is in a bad state then do the following: 

1. Unset the `clipboard` setting. This means future operations will not implicitly use the Windows clipboard
1. Popup a toast dialog saying effectively "VsVim detected the Windows clipboard was in a bad state and reset the clipboard setting" 

Given there is nothing to do once it's corrupted the best option seems to be observably moving away from it.

**Comment by ricksladkey** [comment] 2019-05-03 16:44
@jaredpar but your description doesn't jibe with the symptoms reported in this issue:

> Almost each second copy (y) show me error

So more than half of the yanks succeed. That means the clipboard only in a bad state intermittently, not permanently.

**Comment by jaredpar** [comment] 2019-05-03 17:02
@ricksladkey 

Sure but other issues, like #1663, have reported hangs. It's not entirely clear if it's a hang from our back off logic or a hang in the clipboard itself. I have a suspicion that it's the latter though. 

> That means that if the clipboard is in a bad state, it is only in a bad state intermittently, not permanently.

There have been other reports where it's always broken, or broken just once. I really wish I could find a way to make sense of all of it. Taken as a whole it seems to get into lots of different broken states. That's what makes this so hard to figure out a good way to handle.

Maybe just add a popup whenever we hit an error here, suggest unsetting `clipboard=unnamed` if it persists.

**Comment by ricksladkey** [comment] 2019-05-03 18:00
Well, now I know more about the clipboard than I ever wanted to know.

First, using IlSpy I discovered that `System.Windows.Clipboard` will retry automatically ten times with 100ms delays, so our retries are on top of that underlying retry mechanism. So the total timeout the way we are doing it could be as high as 5.5 seconds if the clipboard is totally wedged.

Second, all the issues reporting these VsVim errors (e.g. #1663) also report that the copy to the clipboard actually succeeds regardless of the error.

Third, many application developers (e.g. on stackoverflow) report that simply ignoring the exception never produces a bug report of the type "copy to clipboard silently fails".

All of this seems to suggest that we should remove our retry loop and silently ignore any clipboard exceptions we encounter. I know this seems heavy-handed but practically speaking, if the copy succeeds even when an exception occurs, we are making the user miserable for no concrete benefit. And if the clipboard is well and truly wedged, then it's a systemic problem with a shared resource and the symptoms should be readily apparent even though we don't report the exception.

**Comment by jaredpar** [comment] 2019-05-04 15:03
> First, using IlSpy I discovered that System.Windows.Clipboard will retry automatically ten times with 100ms delays, so our retries are on top of that underlying retry mechanism. 

The retry only exists for certain versions of .NET Framework. Believe that for 4.6 and before, maybe it was 4.5, there is no underlying retry which is why I added the logic. But yeah with more recent .NET Framework installations there is a retry so our layer is redundant. 

At this point I think we can safely assume we run on a .NET Framework that has the retry code and delete our layer. The number of developers running 4.6 and before is incredibly small at this point.

**Closed** 2019-05-08 20:11 UTC
Labels: bug
