### ISSUE TITLE
Macros do not record and/or execute backspaces

### ISSUE THREAD

**Issue by jmegner** [VsVim/VsVim#2653] opened 2019-06-19 22:01 UTC
**Describe the bug**
If you record a macro where you go in insert mode and do some backspaces, then executing the macro does not include the backspaces.

**To Reproduce**

1.  Record a macro to register w that appends "asdf" to end of line and backspaces 4 times (keystrokes are "qwAasdf\<Backspace\>\<Backspace\>\<Backspace\>\<Backspace\>\<Escape\>q")
2. Notice that the end result of what you recorded is to go to the end of the line since the appended characters were backspaced.
3.  Execute the w macro using "@w".
4.  Notice that "asdf" is appended to the end of your current line for each time you execute the macro.  The macro should have just moved your cursor to the end of the line.

**Environment:**

- Visual Studio version: MS VS2015 Enterprise, v14.0.25431.01 Update 3
- VsVim version: 2.7.0.0
- Check(Type 'x') any that are installed:
    - [ ] ReSharper
    - [ ] Visual Assist

**Comment by ricksladkey** [comment] 2019-06-20 01:40
It might be that VsVim cannot record macro keys that are assigned to be handled by Visual Studio. Can you check whether <kbd>CTRL</kbd>+<kbd>H</kbd> is set to "Handled by VsVim" in the keyboard configuration?

![image](https://user-images.githubusercontent.com/2680524/59811977-26068c80-92da-11e9-8009-47adbf8309b2.png)

Can you report the output of the `:register w` command? It should be something like this:

```
--- Registers ---
"w   Aasdf<BS><BS><BS><BS><Esc>
```

**Comment by jmegner** [comment] 2019-06-20 14:14
>Can you check whether CTRL+H is set to "Handled by VsVim" in the keyboard configuration?

I went to Tools > Options > VsVim > Keyboard, then checkmarked "Include All Scopes", and I did not see an entry for CTRL+H.  The list was {... , CTRL+G, CTRL+Home, CTRL+K, ...}.  Is this list dynamically generated based on detecting conflicts?

>Can you report the output of the :register w command?
Here:
```
--- Registers ---
"w   Aasdf<BS><Esc>
```

**Comment by ricksladkey** [comment] 2019-07-07 19:03
Yes, that dialog lists **only** those keys that actually conflict.

If you are still interested in figuring this out, can you turn collect some data for me?

- Turn on the VsVim output window in settings
- Try to record and replay the macro
- Turn off the VsVim output window
- Paste the contents of the VsVim output window to this issue

Thanks.

**Comment by jmegner** [comment] 2019-07-07 22:03
```
VsVim VimKeyProcessor::KeyDown Q None None
VsVim VimKeyProcessor::KeyDown Handled = False
VsVim VimKeyProcessor::TextInput Text=q ControlText= SystemText=
VsVim VimBuffer.Process: q:RawCharacter:None
VsVim VimKeyProcessor::TextInput Handled=True
VsVim VimBufferCoordinator::PreviewKeyUp Q
VsVim VimKeyProcessor::KeyUp Q None
VsVim VimKeyProcessor::KeyUp Handled = False
VsVim VimBufferCoordinator::KeyUp Q
VsVim VimKeyProcessor::KeyDown W None None
VsVim VimKeyProcessor::KeyDown Handled = False
VsVim VimKeyProcessor::TextInput Text=w ControlText= SystemText=
VsVim VimBuffer.Process: w:RawCharacter:None
VsVim VimKeyProcessor::TextInput Handled=True
VsVim VimBufferCoordinator::PreviewKeyUp W
VsVim VimKeyProcessor::KeyUp W None
VsVim VimKeyProcessor::KeyUp Handled = False
VsVim VimBufferCoordinator::KeyUp W
VsVim VimKeyProcessor::KeyDown RightShift None Shift
VsVim VimKeyProcessor::KeyDown Handled = False
VsVim VimKeyProcessor::KeyDown A None Shift
VsVim VimKeyProcessor::KeyDown Handled = False
VsVim VimKeyProcessor::TextInput Text=A ControlText= SystemText=
VsVim VimBuffer.Process: A:RawCharacter:None
VsVim Open Linked Undo Transaction: Insert
VsVim VimKeyProcessor::TextInput Handled=True
VsVim VimBufferCoordinator::PreviewKeyUp A
VsVim VimKeyProcessor::KeyUp A Shift
VsVim VimKeyProcessor::KeyUp Handled = False
VsVim VimBufferCoordinator::KeyUp A
VsVim VimBufferCoordinator::PreviewKeyUp RightShift
VsVim VimKeyProcessor::KeyUp RightShift None
VsVim VimKeyProcessor::KeyUp Handled = False
VsVim VimBufferCoordinator::KeyUp RightShift
VsVim VimKeyProcessor::KeyDown A None None
VsVim VimKeyProcessor::KeyDown Handled = False
VsVim VimKeyProcessor::TextInput Text=a ControlText= SystemText=
VsVim VimKeyProcessor::TextInput Handled=False
VsVim VsCommandTarget::Exec UserInput Key.RawCharacter: 1496a755-94de-11d0-8c3f-00c04fc2aae2 1
VsVim VimBuffer.Process: a:RawCharacter:None
VsVim TryCustomProcess Insert "a" and completion False
VsVim OnTextChange: 1
VsVim OnTextChange: change 0
VsVim OnTextChange: old = '', new = 'a'
VsVim OnTextChange: old = '[7751..7751)', new = '[7751..7752)'
VsVim OnTextChange: caret position = 7751
VsVim VimBufferCoordinator::PreviewKeyUp A
VsVim VimKeyProcessor::KeyUp A None
VsVim VimKeyProcessor::KeyUp Handled = False
VsVim VimBufferCoordinator::KeyUp A
VsVim VimKeyProcessor::KeyDown S None None
VsVim VimKeyProcessor::KeyDown Handled = False
VsVim VimKeyProcessor::TextInput Text=s ControlText= SystemText=
VsVim VimKeyProcessor::TextInput Handled=False
VsVim VsCommandTarget::Exec UserInput Key.RawCharacter: 1496a755-94de-11d0-8c3f-00c04fc2aae2 1
VsVim VimBuffer.Process: s:RawCharacter:None
VsVim TryCustomProcess Insert "s" and completion True
VsVim OnTextChange: 1
VsVim OnTextChange: change 0
VsVim OnTextChange: old = '', new = 's'
VsVim OnTextChange: old = '[7752..7752)', new = '[7752..7753)'
VsVim OnTextChange: caret position = 7752
VsVim VimBufferCoordinator::PreviewKeyUp S
VsVim VimKeyProcessor::KeyUp S None
VsVim VimKeyProcessor::KeyUp Handled = False
VsVim VimBufferCoordinator::KeyUp S
VsVim VimKeyProcessor::KeyDown D None None
VsVim VimKeyProcessor::KeyDown Handled = False
VsVim VimKeyProcessor::TextInput Text=d ControlText= SystemText=
VsVim VimKeyProcessor::TextInput Handled=False
VsVim VsCommandTarget::Exec UserInput Key.RawCharacter: 1496a755-94de-11d0-8c3f-00c04fc2aae2 1
VsVim VimBuffer.Process: d:RawCharacter:None
VsVim TryCustomProcess Insert "d" and completion True
VsVim OnTextChange: 1
VsVim OnTextChange: change 0
VsVim OnTextChange: old = '', new = 'd'
VsVim OnTextChange: old = '[7753..7753)', new = '[7753..7754)'
VsVim OnTextChange: caret position = 7753
VsVim VimBufferCoordinator::PreviewKeyUp D
VsVim VimKeyProcessor::KeyUp D None
VsVim VimKeyProcessor::KeyUp Handled = False
VsVim VimBufferCoordinator::KeyUp D
VsVim VimKeyProcessor::KeyDown F None None
VsVim VimKeyProcessor::KeyDown Handled = False
VsVim VimKeyProcessor::TextInput Text=f ControlText= SystemText=
VsVim VimKeyProcessor::TextInput Handled=False
VsVim VsCommandTarget::Exec UserInput Key.RawCharacter: 1496a755-94de-11d0-8c3f-00c04fc2aae2 1
VsVim VimBuffer.Process: f:RawCharacter:None
VsVim TryCustomProcess Insert "f" and completion True
VsVim OnTextChange: 1
VsVim OnTextChange: change 0
VsVim OnTextChange: old = '', new = 'f'
VsVim OnTextChange: old = '[7754..7754)', new = '[7754..7755)'
VsVim OnTextChange: caret position = 7754
VsVim VimBufferCoordinator::PreviewKeyUp F
VsVim VimKeyProcessor::KeyUp F None
VsVim VimKeyProcessor::KeyUp Handled = False
VsVim VimBufferCoordinator::KeyUp F
VsVim VsCommandTarget::Exec UserInput Key.Back: 1496a755-94de-11d0-8c3f-00c04fc2aae2 2
VsVim OnTextChange: 1
VsVim OnTextChange: change 0
VsVim OnTextChange: old = 'f', new = ''
VsVim OnTextChange: old = '[7754..7755)', new = '[7754..7754)'
VsVim OnTextChange: caret position = 7755
VsVim VimBufferCoordinator::PreviewKeyUp Back
VsVim VimKeyProcessor::KeyUp Back None
VsVim VimKeyProcessor::KeyUp Handled = False
VsVim VimBufferCoordinator::KeyUp Back
VsVim VsCommandTarget::Exec UserInput Key.Back: 1496a755-94de-11d0-8c3f-00c04fc2aae2 2
VsVim OnTextChange: 1
VsVim OnTextChange: change 0
VsVim OnTextChange: old = 'd', new = ''
VsVim OnTextChange: old = '[7753..7754)', new = '[7753..7753)'
VsVim OnTextChange: caret position = 7754
VsVim VimBufferCoordinator::PreviewKeyUp Back
VsVim VimKeyProcessor::KeyUp Back None
VsVim VimKeyProcessor::KeyUp Handled = False
VsVim VimBufferCoordinator::KeyUp Back
VsVim VsCommandTarget::Exec UserInput Key.Back: 1496a755-94de-11d0-8c3f-00c04fc2aae2 2
VsVim OnTextChange: 1
VsVim OnTextChange: change 0
VsVim OnTextChange: old = 's', new = ''
VsVim OnTextChange: old = '[7752..7753)', new = '[7752..7752)'
VsVim OnTextChange: caret position = 7753
VsVim VimBufferCoordinator::PreviewKeyUp Back
VsVim VimKeyProcessor::KeyUp Back None
VsVim VimKeyProcessor::KeyUp Handled = False
VsVim VimBufferCoordinator::KeyUp Back
VsVim VsCommandTarget::Exec UserInput Key.Back: 1496a755-94de-11d0-8c3f-00c04fc2aae2 2
VsVim OnTextChange: 1
VsVim OnTextChange: change 0
VsVim OnTextChange: old = 'a', new = ''
VsVim OnTextChange: old = '[7751..7752)', new = '[7751..7751)'
VsVim OnTextChange: caret position = 7752
VsVim VimBufferCoordinator::PreviewKeyUp Back
VsVim VimKeyProcessor::KeyUp Back None
VsVim VimKeyProcessor::KeyUp Handled = False
VsVim VimBufferCoordinator::KeyUp Back
VsVim VsCommandTarget::Exec UserInput Key.Escape: 1496a755-94de-11d0-8c3f-00c04fc2aae2 103
VsVim VimBuffer.Process: ^[:Escape:None
VsVim Complete Linked Undo Transaction: Insert
VsVim TryCustomProcess CompleteMode true and completion False
VsVim VimBufferCoordinator::PreviewKeyUp Escape
VsVim VimKeyProcessor::KeyUp Escape None
VsVim VimKeyProcessor::KeyUp Handled = False
VsVim VimBufferCoordinator::KeyUp Escape
VsVim VimKeyProcessor::KeyDown Q None None
VsVim VimKeyProcessor::KeyDown Handled = False
VsVim VimKeyProcessor::TextInput Text=q ControlText= SystemText=
VsVim VimBuffer.Process: q:RawCharacter:None
VsVim VimKeyProcessor::TextInput Handled=True
VsVim VimBufferCoordinator::PreviewKeyUp Q
VsVim VimKeyProcessor::KeyUp Q None
VsVim VimKeyProcessor::KeyUp Handled = False
VsVim VimBufferCoordinator::KeyUp Q
```

**Comment by ricksladkey** [comment] 2019-07-11 05:22
@jmegner When you type `asdf` I can see from the log that some completion becomes active. There might be an option you can use. I'm not very familiar with this option or what problem it solves, but can you try setting "Clean Macro Recording" to "True" in VsVim Settings -> Vim Edit Behavior and repeat your experiment?

The other thing you can do is observe carefully as you type and see if some "non-invasive" completion is coming up. In any case, I'm pretty sure now that the completion is the cause of the difference between when you fail to record it and I succeed in recording it.

**Comment by jmegner** [comment] 2019-07-11 14:46
>see if some "non-invasive" completion is coming up

Not exactly sure about all the different flavors of completion, but yes, completion suggestions pop up if and only if "Clean Macro Recording" is "False".  Following screenshot is from typing in a .cs file:

![image](https://user-images.githubusercontent.com/539362/61059687-0c2f0580-a3bf-11e9-8828-a3a86252e5ff.png)

>can you try setting "Clean Macro Recording" to "True" in VsVim Settings -> Vim Edit Behavior and repeat your experiment?

With CleanMacroRecording=False, I get completion suggestions and the macro executes incorrectly.  With CleanMacroRecording=True, I do not get completion suggestions and the macro executes correctly.

On a personal note, I will keep CleanMacroRecording=True for my usage.  Up to you on whether completion-suggestions breaking macros should be considered a bug given that there's a really good workaround.

**Comment by ricksladkey** [comment] 2019-07-11 19:00
Marking this a duplicate of #983. I may try to find a way to improve macro recording when "Clean Macro Recording" is **not** set. If you would like than feature, fee free to create a new issue.

**Closed by ricksladkey** 2019-07-11 19:00 UTC
Labels: duplicate, visual studio integration

**Comment by jmegner** [comment] 2019-07-12 14:16
Oh, also, thanks for giving me the excellent workaround.
