### ISSUE TITLE
VsVim for Mac: Vim commands not enabled when editing T4 templates 

### ISSUE THREAD

**Issue by coolbluewater** [VsVim/VsVim#2816] opened 2020-04-12 15:43 UTC
To repro, open a T4 template (.tt file).
Expect: Vim commands to work
Actual: Vim commands don't work. I believe they worked in some past version of VsMac+VsVim.

Visual Studio for Mac: 8.5.3 (build 13)
VsVim version 2.8.0.5
Also have the Text Templating IDE extension: 8.5.2.

**Comment by nosami** [comment] 2020-04-12 16:16
I just tried VSMac 8.5.2.13 and 8.6 with VsVim 2.8.0.7

Both were working with `Add -> New File -> T4 Template`

**Comment by coolbluewater** [comment] 2020-04-12 16:53
Ok, I disabled the "Text Templating" extension (which adds syntax highlighting) and now the Vim commands appear.

Any idea why the commands are disabled when this extension is loaded?

**Comment by nosami** [comment] 2020-04-12 17:38
@coolbluewater 

OK. Now I see what is going on. T4 templates are still using the old editor, so you would need to use the XSVim extension for vim keys to work there. That is why it was working for me.

tip: It's quite hard to visibly see the difference between the old editor and the new editor, but if you turn on the "Show indentation guides" setting, you can see the difference. 
<img width="575" alt="image" src="https://user-images.githubusercontent.com/667194/79075774-b2ac8c00-7cec-11ea-9426-42dd82f3084e.png">

The new editor has a dashed line, whereas the old editor shows a dotted line.

<img width="721" alt="image" src="https://user-images.githubusercontent.com/667194/79075749-990b4480-7cec-11ea-88ed-1f09ab37770d.png">

**Comment by nosami** [comment] 2020-04-12 17:43
Also, with the XSVim extension. The caret shows the background and foreground colours "inverted" - 
<img width="122" alt="image" src="https://user-images.githubusercontent.com/667194/79075886-788fba00-7ced-11ea-83d7-a1997398cc9b.png">

This is something I still need to implement with the VSVim extension.

**Comment by coolbluewater** [comment] 2020-04-12 18:02
Hmm - I don't have XSVim installed anymore, but the Vim commands do work when I disable the text templating extension . Does disabling that extension cause the editor to switch to the new editor? Weird...

Also I don't see XSVim in the Gallery anymore, has it been removed?

**Comment by nosami** [comment] 2020-04-12 18:33
> Does disabling that extension cause the editor to switch to the new editor?

I can't see how :) But you can check by looking at the indentation guide like my picture above.

> Also I don't see XSVim in the Gallery anymore, has it been removed?

Yeah, I removed it from the feed to try and reduce any confusion :) You can still install it manually though from here https://github.com/nosami/XSVim/releases/download/0.65.12.81/XSVim.XSVim_0.65.12.81.mpack

**Comment by coolbluewater** [comment] 2020-04-13 06:56
> I can't see how :) But you can check by looking at the indentation guide like my picture above.

There's no indentation guide at all. But the cursor is the full-block cursor, no inverted colors. So it does look like something odd is happening. The Visual Studio team might be interested in knowing about this.

I went ahead and installed XSVim and now editing T4 templates with the Text Templating extension enabled does work.

Might be worth keeping this one open so that people can find it, or otherwise adding a note in the VSVim release notes with a pointer to the XSVim install path you mentioned.

Thanks!

**Comment by nosami** [comment] 2021-04-24 09:04
I'm closing this issue as it's not really related to VsVim.

The problem is that .tt files are still using the old editor in VSMac and so this extension is not being used. As a workaround, you can use the XSVim extension when you are working with .tt files

**Closed by nosami** 2021-04-24 09:04 UTC
Labels: vs4mac integration
