### ISSUE TITLE
Cannot change block caret color

### ISSUE THREAD

**Issue by farzadmf** [VsVim/VsVim#2400] opened 2018-10-24 12:54 UTC
Hi,

Today, I'm facing an issue with VsVim where my block caret is now black. I tried to set the color in **Item Colors** in settings, but the weird thing is that when I change it and click OK, the color is still black, and when I come back to the settings window, the setting has been reverted back to its previous value.

Example:
1. I open VS, the caret in VS is black
2. I go to the settings and change `Block Caret Background` (which is now `Black`) to `Yellow` (just to test)
3. I click OK, the caret is still black
4. I come back to the settings and `Block Caret Background` is set to `Black` again!

One thing that might be important is that the first time I opened VS today, I saw an exception saying something like "the error may be because of an exception"; I'm used to exceptions appearing from time to time, but maybe this one caused something to change and now VsVim cannot save its settings?!

I appreciate if you help me

**Comment by ricksladkey** [comment] 2018-10-24 15:37
I'm sorry to hear about that. Can you perform a couple of experiments for me to narrow down where the problem is?

First, can you successfully change other VsVim colors from the settings window, like the command margin foreground/background?

![image](https://user-images.githubusercontent.com/2680524/47442652-ae02b980-d780-11e8-873b-1e10d493aa97.png)

Second, does trying to change the block caret background color through the Visual Studio settings work or behave any differently?

Tools -> Options -> Environment -> Fonts and Colors -> Display Items -> VsVim Block Caret -> Item Background

![image](https://user-images.githubusercontent.com/2680524/47442853-1b164f00-d781-11e8-9a33-17fd8e752a04.png)

**Comment by adamskt** [comment] 2018-10-24 16:40
I ran into the same situation today, and the VsVim options do not appear in the Fonts and Colors "Display Items" listing in Tools -> Options -> Environment:
![screenshot from 2018-10-24 09-30-04](https://user-images.githubusercontent.com/105415/47446148-717a9200-d76f-11e8-94b1-61647d886c25.png)

I did see the plugin exception prior and restarted Visual Studio.  The relevant lines from ActivityLog.xml are:
```
CreateInstance failed for package [Vim.VisualStudio.VsVimPackage, VsVim, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]Source: 'mscorlib' Description: Could not load file or assembly 'file:///c:\users\kellyadams\appdata\local\microsoft\visualstudio\15.0_f847dbb5\extensions\42ka1uwz.afy\VsVim.dll' or one of its dependencies. The system cannot find the file specified. System.IO.FileNotFoundException: Could not load file or assembly 'file:///c:\users\kellyadams\appdata\local\microsoft\visualstudio\15.0_f847dbb5\extensions\42ka1uwz.afy\VsVim.dll' or one of its dependencies. The system cannot find the file specified.
```
Visual Studio version info:
[VisualVersionInfo.txt](https://github.com/jaredpar/VsVim/files/2511416/VisualVersionInfo.txt)

**Comment by adamskt** [comment] 2018-10-24 16:41
FWIW, a uninstall/reinstall of the VsVIM VSIX has remedied the issue.

**Comment by farzadmf** [comment] 2018-10-24 17:47
Thank you @ricksladkey for your answer, and thank you @adamskt for pointing out the problem. That's exactly the problem that I had, and it was very confusing for me that the options disappeared from `Fonts and Colors`!

But anyway, as suggested by @adamskt , I uninstalled/installed `VsVim`, and it seems to be fine now.

I can close this issue if you guys don't want to keep it open to investigate

**Comment by mattscully** [comment] 2018-10-24 18:02
I'm wondering if this might be happening for everyone that uses the Dark theme and just upgraded to the latest version of VsVim.  It happened for me, too.  It could be that a fix is still worth it, unless it is recommended for everyone to have to reinstall the extension.

**Comment by ricksladkey** [comment] 2018-10-24 20:37
@farzadmf  Please leave this issue open until we determine what the conditions are that produces it. If there is some way of avoid the burdensome uninstall/reinstall, that would be preferable to a workaround.

@jaredpar Does this symptom ring any bells, i.e. fonts and colors issues with extensions? I believe at the "fonts and colors" level, the only obvious change from 2.5 to 2.6 is that the `EditorFormatDefinition` for `vsvim_blockcaret` changed to allow the foreground to be customizable:

```diff
index 34f18c8e..4de424bd 100644
--- a/Src/VimWpf/Implementation/BlockCaret/BlockCaretFormatDefinition.cs
+++ b/Src/VimWpf/Implementation/BlockCaret/BlockCaretFormatDefinition.cs
@@ -18,8 +18,8 @@ namespace Vim.UI.Wpf.Implementation.BlockCaret
         internal BlockCaretFormatDefinition()
         {
             DisplayName = "VsVim Block Caret";
-            ForegroundColor = Colors.Black;
-            BackgroundCustomizable = false;
+            ForegroundColor = Colors.White;
+            BackgroundColor = Colors.Black;
         }
     }
 }
```

**Comment by jaredpar** [comment] 2018-10-25 18:31
For anyone who saw the dialog about an exception in an extension can you do the following:

1. Install this extension https://marketplace.visualstudio.com/items?itemName=MadsKristensen.ClearMEFComponentCache
1. Under Tools menu there will be an option "Show MEF Errors"

Can you paste back the output of that menu? If there is a composition issue that will have the relevant log and give us the info we need.

**Comment by farzadmf** [comment] 2018-10-25 18:45
Hey @ricksladkey, I'm not sure 100%, but I *think* VsVim was working properly; only the caret color was weird

@Wojnach For me, re-installing VsVim resulted in the options to become available, and then I needed to change the color manually

And @jaredpar , thank you for the suggestion, I think the extension would be useful in any case

**Comment by jaredpar** [comment] 2018-10-25 23:56
@Wojnach 

Thanks for posting that. That particular error is benign. I will look and see if I can make this go away. But at the same time it's not causing any issues here.

**Comment by ricksladkey** [comment] 2018-10-26 02:36
@Wojnach The old foreground color was used as the background the old background color was unused. VsVim now uses the foreground color for the foreground and the background color as the background, which makes a lot more sense. The default color selection looks correct only with the light theme.

The net effect with the old version and the new version is that the actual default background color of the caret was and is still black. This was always bad for the dark theme, but at least you could change it.

The good news is that you can actually read the character under the caret (with any theme) if you choose appropriate contrasting colors. The problem (experienced by some but not all users) is that due to some Visual Studio issue, the VsVim fonts and colors don't exist and therefore cannot be set.

The upshot is that almost all users will have to tweak the caret color for the best results.

I only have access to a limited number of machines and the problem is not showing up on those machines so I am trying to reconstruct what could be happening on the installations that exhibit the problem. I feel pretty crummy about the whole issue, since the whole ideas was to improve the caret colors for everybody not make the caret worse for anybody.

**Comment by jaredpar** [comment] 2018-10-26 17:40
Chatted with a few people and to fix the theming issue we need to get themed colors for this definition. Essentially a color which will change based on the theme. The process is documented at this link:

https://docs.microsoft.com/en-us/visualstudio/extensibility/internals/color-theming-tools?view=vs-2017

I haven't had a chance to digest this fully yet. At a glance though it looks like it's pretty straight forward.

**Comment by ricksladkey** [comment] 2018-10-26 18:49
@jared Theming is a good idea, but will only reduce the number of users who have to configure VsVim fonts and colors. The bug here is that it is impossible to set the colors. In other words, the VsVim fonts and colors should "show up" in Tools -> Environment -> Fonts and Colors without having to uninstall and reinstall the VsVim extension.

I am more and more convinced that this is a MEF issue and would really like a complete Visual Studio activity log for a system exhibiting the problem. See the first report from @adamskt above.

**Comment by adamskt** [comment] 2018-10-26 19:06
@ricksladkey I did save my ActivityLog.xml, I hope the signal/noise ratio isn't too high for you :)
[ActivityLog.zip](https://github.com/jaredpar/VsVim/files/2520531/ActivityLog.zip)

**Comment by jaredpar** [comment] 2018-10-26 20:13
@adamskt thanks for providing that. That gives a clue to what's going on. The MEF error log would help me narrow it down to a more specific area. Can you do the following:

1. Install this extension https://marketplace.visualstudio.com/items?itemName=MadsKristensen.ClearMEFComponentCache
1. Under Tools menu there will be an option "Show MEF Errors"

Can you paste back the output of that menu?

**Comment by jaredpar** [comment] 2018-10-26 20:29
@ricksladkey 

> I am more and more convinced that this is a MEF issue 

That was my initial thought as well. The data though is a bit confusing.  Here is the first error from @adamskt log:

```
 Exception occurred while loading assembly Vim.VisualStudio.Shared, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null: System.IO.FileNotFoundException: Could not load file or assembly &apos;Vim.VisualStudio.Shared, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null&apos; or one of its dependencies. The system cannot find the file specified.&#x000D;&#x000A;File name: &apos;Vim.VisualStudio.Shared, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null&apos;&#x000D;&#x000A;   at
 System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark&amp; stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)&#x000D;&#x000A;   at
 System.Reflection.RuntimeAssembly.nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark&amp; stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)&#x000D;&#x000A;   at
 System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, Evidence assemblySecurity, RuntimeAssembly reqAssembly, StackCrawlMark&amp; stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)&#x000D;&#x000A;   at
 Microsoft.VisualStudio.ExtensibilityHosting.FaultCatchingAssemblyLoader.&lt;&gt;c__DisplayClass17_0.&lt;LoadAssembly&gt;b__0(AssemblyName assemblyNameParam)&#x000D;&#x000A;&#x000D;&#x000A;WRN: Assembly binding logging is turned OFF.&#x000D;&#x000A;To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.&#x000D;&#x000A;Note: There is some performance penalty associated with assembly bind failure logging.&#x000D;&#x000A;To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].&#x000D;&#x000A;.;vs.platform.extensibilityhosting.assemblyloadexception.AssemblyFullName=Vim.VisualStudio.Shared, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null;vs.platform.extensibilityhosting.assemblyloadexception.AssemblyPath=file:///C:/USERS/KELLYADAMS/APPDATA/LOCAL/MICROSOFT/VISUALSTUDIO/15.0_F847DBB5/EXTENSIONS/42KA1UWZ.AFY/Vim.VisualStudio.Shared.dll;vs.platform.extensibilityhosting.assemblyloadexception.FusionLogEntry=WRN: Assembly binding logging is turned OFF.&#x000D;&#x000A;To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.&#x000D;&#x000A;Note: There is some performance penalty associated with assembly bind failure logging.&#x000D;&#x000A;To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].&#x000D;&#x000A;;vs.platform.extensibilityhosting.assemblyloadexception.ExceptionType=System.IO.FileNotFoundException;vs.platform.extensibilityhosting.assemblyloadexception.ExceptionMessage=Could not load file or assembly &apos;Vim.VisualStudio.Shared, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null&apos; or one of its dependencies. The system cannot find the file specified.;vs.platform.extensibilityhosting.assemblyloadexception.ExceptionStackTrace=   at
```

Two interesting take aways from that:

1. The load of Vim.VisualStudio.Shared is done via `Load(AssemblyName)`.  That means VS fully expects the directory holding the VsVim binaries to be in the current probing path else it would have done a `LoadFrom(string)`. 
1. The exception is `FileNotFoundException` which suggests it's not actually in the probing path. That or the extension is only partially installed.

One possibly explanation for this is that it's actually a pkgdef problem. Essentially VS is seeing data in the pkgdef (loaded statically not with the assembly) that causes it to do a MEF query before MEF has loaded VsVim. Been a long time since I've seen that though. I've done what checking I can to eliminate that possibility. 

I'm going to ask around and see if I can understand a bit better how MEF composition works in more recent versions of VS. Too much of my mental model is built around the VS2010 version which is substantially different than the new one.

**Comment by ricksladkey** [comment] 2018-10-29 04:48
@adamskt Thanks for the log. Ha, ha, yes, there are literally 20,000+ stack frames in that activity log. However, it call all be summarized by:

- Some problem loading Vim.VisualStudio.Shared or one of its dependencies
- Likely the same problem loading Vim.UI.WPF
- Some other problem loading the VsVim package

Unfortunately, I did not gain any major insight into what is going wrong.

**Comment by eviltobz** [comment] 2018-10-29 10:53
Hmmm, I was having this problem with the colours all sticking to black whilst running the dark theme. Restarting Studio didn't help me change the colours, but just installing that MEF error tool & re-restarting Studio fixed the problem for me - it suddenly went back to a varied bunch of colours which I presume that I set up some time in the past, and I was able to change them to something else successfully too.

**Comment by ricksladkey** [comment] 2018-10-30 00:55
@eviltobz I think your observation supports the idea that there is an ordering difference (effectively a race condition) during the initial caching of the MEF graph. Simply repeating the generation of the MEF graph, either by clearing the MEF cache, uninstalling and reinstalling VsVim, or installing some other extension might successfully do one or more steps in a different order and avoid the race condition.

**Comment by ricksladkey** [comment] 2019-05-01 02:21
Closing this issue as the symptoms were not related to the new functionality at the time.

If you experience an error similar to what is reported above, and it cannot be fixed by uninstalling and reinstalling VsVim, please open a new issue.

**Closed by ricksladkey** 2019-05-01 02:21 UTC
