### ISSUE TITLE
VSIX installer sees AmtelStudio and not Visual Studio 2017

### ISSUE THREAD

**Issue by 4a-42** [VsVim/VsVim#2482] opened 2019-04-05 22:17 UTC
I have Amtel Studio 7 and Visual Studio 2017. 

When I download and run VsVim.vsix, it only allows me to install for Amtel Studio.

If I install for Amtel and re-run VsVim.vsix, I get error "This extension is already installed to all applicable products." 

I attempted to download the extension inside VS too. When I try to install the extension via the "Extensions and Updates" menu in Visual Studio, I get error "The remote server returned an error: (403) Forbidden." I assume this could be a firewall issue or something on my end. 

This is basically the opposite problem of #1977

![image](https://user-images.githubusercontent.com/22332960/55659115-d7128600-57c5-11e9-98e6-b2a6108e3e21.png)

**Comment by jaredpar** [comment] 2019-04-08 02:48
Hmm that seems odd. All the VsVim package does is register that it will work in either environment. I wonder if the installer logic changed here to only show the first. @madskristensen may know.

**Comment by madskristensen** [comment] 2019-04-08 15:39
@jaredpar I think VS2019 will not recognize IntegratedShell as an install target anymore.

**Comment by ricksladkey** [comment] 2019-04-27 06:06
The only explanation I can think of that accounts for the described symptoms is that that version of VsVim was in fact already installed on VS2017. Perhaps it was just further down in the list of extensions and disabled?

**Comment by jaredpar** [comment] 2019-04-27 20:50
I think Atmel may have to weigh in here. The approach of listing the integrated shell as a target has worked ever since I started supporting Atmel. If that's not working anymore perhaps Atmel has a better suggestion on what to do.

**Comment by ricksladkey** [comment] 2019-04-27 21:19
To clarify, @jaredpar and @madskristensen, the reported issue has nothing to do per se with Atmel or the integrated shell. The OP reported that Atmel was in fact **working correctly**. The non-working reported problem is with Visual Studio 2017.

**Comment by ricksladkey** [comment] 2019-04-27 21:26
In other words, our task (should we choose to accept it) is to explain why Visual Studio 2017 does **not** appear in the screenshot even though VS2017 is in fact installed on the system. My theory is that the Vsix installer correctly determined that VsVim was **already installed** on VS2017 and therefore does not offer it as an installation target.

**Comment by jaredpar** [comment] 2019-04-27 23:55
Oh I see. That indeed makes no sense here. 

@4a-42 curious: if you open VS2017, look at the installed extensions, is VsVim listed? I would expect even if it's listed that it should still show up in the installer. At this point though want to rule everything out.

**Comment by TKumadaki** [comment] 2019-04-28 01:57
I tested the following.

**CASE: 1**

-  Vs 2017
-  Atmel 7.0
-  VsVim 2.7 (from open gallary)

I double-click on VsVim.vsix.
VsVim was installed on both Vs2017 and Atmel 7.0.
However, VsVim does not run in Atmel.
There are the following messages in "ActivityLog.xml".

"Could not load file or assembly 'Microsoft.VisualStudio.Shell.10. 0, Version = 11.0.0.0, Culture = neutral, PublicKeyToken = b03f5f7f11d50a3a' or one of its dependencies."

This looks like the same situation as #2442

**CASE2:**

-  Atmel 7.0
-  VsVim 2.5, 2.6, 2.7

Only VsVim 2.5 works.
2.6 and 2.7 display the same message as **CASE:1**.

**CASE3:**

-  Vs 2017
-  Atmel 7.0
-  VsVim 2.5

I double-click on VsVim.vsix.
VsVim has been installed on Vs2017 only.
Then I dragged and dropped VsVim.vsix to the following.
`C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\VSIXInstaller.exe`

VsVim has been installed on Atmel 7.0 and has been verified to work properly.

I built a test environment so I can still investigate.
tell me if there is anything I can do.
note that I don't know anything about Atmel Studio.

**Comment by TKumadaki** [comment] 2019-04-28 05:23
I was finally able to reproduce the situation.

1. Install Atmel Studio 7.0.
2. Install VsVim 2.5.
3. Install Visual Studio 2017.
4. Double click on VsVim 2.5 and the following message will be displayed.
"This extenstion is already installed to all applicable products."

I was able to install VsVim on Visual Studio 2017 using one of the following methods:

- Install from Visual Studio "Tools"-> "Extensions and Updates".
- Drag and drop VsVim.vsix to the following path.
"C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\Common7\IDE\VSIXInstaller.exe"

There are multiple VSIXInstaller.exe,
Does it work differently depending on which one starts when I double-click?

In any case, there seems to be a situation where both Vs2017 and Atmel is installed, but only one is displayed in the installer.

**Comment by ricksladkey** [comment] 2019-04-28 06:22
Thanks, @TKumadaki for doing all this work!

When you double-click a Vsix file, only one program can be registered to handle that file type. You can use task manager (or process explorer, etc.) to get the full pathname of the VsixInstaller.exe that runs when you double-click a vsix file. And from your description, that sounds like it is some other version than the one that is co-installed with VS2107.

Ideally the registered Vsix installer should be able to install extensions for any Visual Studio derived product that uses extensions, but that might not always be the case, depending on installation order, product versions, etc.

In any case, I think we have enough information to close this issue. Although it is not ideal, it should always be possible to install a VsVim vsix file into Visual Studio 2017 by explicitly running the VsixInstaller.exe that is co-installed with VS2017.

**Comment by TKumadaki** [comment] 2019-04-28 08:36
"This extenstion is already installed to all applicable products."
The full path of the Vsix installer for which the above message is displayed is as follows.

`C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\VSIXInstaller.exe`

Interestingly, right-click VsVim.vsix ,point to Open with,and click VSIXInstaller.exe for Vs2017,
but it was not possible to install.

It can not be installed without dragging and dropping.

This drag and drop was introduced to the homepage of my country as "How to make sure to install VsVim on Atmel".

**Comment by TKumadaki** [comment] 2019-04-28 10:45
I'm sorry. The following message is incorrect.
"Could not load file or assembly 'Microsoft.VisualStudio.Shell.10. 0, Version = 11.0.0.0, Culture = neutral, PublicKeyToken = b03f5f7f11d50a3a' or one of its dependencies."

It is correctly as follows.
"Could not load file or assembly 'Microsoft.VisualStudio.Shell.11.0, Version=11.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies."

**Comment by ricksladkey** [comment] 2019-05-01 01:30
To summarize this issue, there are multiple VsixInstaller.exe files associated with various versions and flavors of Visual Studio that are installed on any given machine. To reliably install an extension, such as VsVim, using the install program (vs. extension management with Visual Studio), you must:

- open two explorer windows
- one window containing the VsixInstaller.exe file associated with the version of Visual Studio you are trying to install it on
- the other window containing the downloaded VsVim.vsix file
- and then drag and drop the VsVim.vsix file on the VsixInstall.exe file

If even this procedure does not work, we can re-open this issue.

**Closed by ricksladkey** 2019-05-01 01:30 UTC
